version: "3.9"

services:
  sftpgo:
    image: drakkan/sftpgo:v2-alpine-slim
    restart: on-failure
    environment:
      - SFTPGO_SFTPD__HOST_KEYS=/srv/id_ed25519
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=8000
      - SFTPGO_DATA_PROVIDER__DRIVER=memory
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
      - SFTPGO_LOADDATA_FROM=/srv/sftpgo.json
    ports:
      - 2222:2022
      - 80:8000
    volumes:
      - /mnt/NAS1/@data/share:/srv/share
      - /mnt/NAS1/@data/config/sftpgo/id_ed25519:/srv/id_ed25519:ro
      - ./sftpgo/sftpgo-backup.json:/srv/sftpgo.json:ro
  samba:
    build: ./samba
    restart: on-failure
    ports:
      - 445:445
    volumes:
      - /mnt/NAS1/@data/share/scans:/mnt/scans
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
  iperf3:
    build: ./iperf3
    restart: on-failure
    ports:
      - 5201:5201
  ipcamera-mjpeg1: &ipcamera
    build: ./ipcamera
    restart: on-failure
    environment:
      - CAMERA=rtsp://***REMOVED***@192.168.1.131/
  ipcamera-mjpeg2:
    <<: *ipcamera
    environment:
      - CAMERA=rtsp://***REMOVED***@192.168.1.132/
  ipcamera-mjpeg3:
    <<: *ipcamera
    environment:
      - CAMERA=rtsp://***REMOVED***@192.168.1.127/
  ipcamera-nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - ./ipcamera/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ipcamera/www/:/var/www/:ro
    depends_on: [ipcamera-mjpeg1, ipcamera-mjpeg2]
