version: "3.9"

services:
  http-server:
    image: python:3.9.5-alpine3.13
    command: python3 -m http.server --directory /mnt 8080
    ports:
      - 8080:8080
    volumes:
      - /mnt/NAS1_DATA/files/www/:/mnt
