version: "3.9"

services:
  sftpgo:
    image: drakkan/sftpgo:v2-alpine-slim
    restart: unless-stopped
    environment:
      - SFTPGO_SFTPD__HOST_KEYS=/srv/id_ed25519
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=8000
      - SFTPGO_DATA_PROVIDER__DRIVER=memory
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
      - SFTPGO_LOADDATA_FROM=/srv/sftpgo.json
    ports:
      - 2222:2022
      - 80:8000
    volumes:
      - /mnt/NAS1/@data/share:/srv/share
      - /mnt/NAS1/@data/config/sftpgo/id_ed25519:/srv/id_ed25519:ro
      - ./sftpgo/sftpgo-backup.json:/srv/sftpgo.json:ro
  samba:
    build: ./samba
    restart: unless-stopped
    ports:
      - 445:445
    volumes:
      - /mnt/NAS1/@data/share/scans:/mnt/scans
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
  iperf3:
    build: ./iperf3
    restart: unless-stopped
    ports:
      - 5201:5201
  ipcamera-mjpeg1: &ipcamera
    build: ./ipcamera
    restart: unless-stopped
    ports:
      - 9001:9000
    environment:
      - CAMERA=rtsp://***REMOVED***@192.168.1.131/
  ipcamera-mjpeg2:
    <<: *ipcamera
    ports:
      - 9002:9000
    environment:
      - CAMERA=rtsp://***REMOVED***@192.168.1.132/
