version: "3.9"

services:
  sftpgo:
    image: drakkan/sftpgo:v2-alpine-slim
    restart: always
    environment:
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=8000
      - SFTPGO_DATA_PROVIDER__DRIVER=memory
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
      - SFTPGO_LOADDATA_FROM=/srv/sftpgo.json
    ports:
      - 2222:2022
      - 80:8000
    volumes:
      - /mnt/NAS1/@data/share:/srv/share
      - ./sftpgo/sftpgo-backup.json:/srv/sftpgo.json
  samba:
    build: ./samba
    restart: always
    ports:
      - 445:445
    volumes:
      - /mnt/NAS1/@data/share/scans:/mnt/scans
      - ./samba/smb.conf:/etc/samba/smb.conf
  iperf3:
    build: ./iperf3
    restart: always
    ports:
      - 5201:5201
